project: 
  type: website

website: 
  page-navigation: true
  title: "ManyBabies Data Simulation and Power Analysis" 
  site-url: "https://github.com/4CCoxAU/PowerAnalysisWorkshopManyBabies" 
  repo-url: "https://github.com/4CCoxAU/PowerAnalysisWorkshopManyBabies"
  repo-actions: [source]
  
  page-footer:
    right: ""
    left: ""
  
  sidebar:
    background: "#D9E3E4"
    logo: ""
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://manybabies.org/
        text: "ManyBabies Power Analysis Workshop"
      - icon: github
        href: https://github.com/4CCoxAU/PowerAnalysisWorkshopManyBabies
        text: "ManyBabies Github"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - href: content/DataSimulation_01.qmd
        text: Part I, Data Simulation
      - href: content/SimulationBasedPowerAnalysis_02.qmd
        text: Part II, Simulation-Based Power Analysis
      - href: content/GridSearch_03.qmd
        text: Part III, Grid Searches and Sensitivity Analyses
      - href: content/FurtherResources.qmd
        text: Further Resources
        
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 2
    toc-expand: 2
    number-sections: true


filters:
  - include-files.lua
  - quarto

  
